[package]
authors = ["Sayan Nandan <ohsayan@outlook.com>"]
build = "build.rs"
edition = "2018"
name = "skyd"
version = "0.7.1"

[dependencies]
# internal deps
libsky = { path = "../libsky" }
sky_macros = { path = "../sky-macros" }
skytable = { git = "https://github.com/skytable/client-rust", branch = "next", default-features = false }
# external deps
ahash = "0.7.6"
bytes = "1.1.0"
chrono = "0.4.19"
clap = { version = "2.33.3", features = ["yaml"] }
env_logger = "0.9.0"
hashbrown = { version = "0.11.2", features = ["raw"] }
log = "0.4.14"
num_cpus = "1.13.0"
openssl = { version = "0.10.38", features = ["vendored"] }
parking_lot = "0.11.2"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.13.0", features = ["full"] }
tokio-openssl = "0.6.3"
toml = "0.5.8"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
# external deps
jemallocator = "0.3.2"
[target.'cfg(target_os = "windows")'.dependencies]
# external deps
winapi = { version = "0.3.9", features = ["fileapi"] }

[target.'cfg(unix)'.build-dependencies]
# external deps
cc = "1.0.71"

[dev-dependencies]
# internal deps
libstress = { path = "../libstress" }
skytable = { git = "https://github.com/skytable/client-rust", features = [
  "async",
  "aio-ssl",
], default-features = false, branch = "next" }
# external deps
bincode = "1.3.3"
rand = "0.8.4"
tokio = { version = "1.13.0", features = ["test-util"] }
[target.'cfg(unix)'.dependencies]
# external deps
libc = "0.2.106"

[features]
nightly = []
